export const SET_SEARCHED_TODOS = 'SET_SEARCHED_TODOS';
export const ADD_TODO = 'ADD_TODO';
export const SET_ACTIVE_DURATIONS = 'SET_ACTIVE_DURATIONS';
export const SET_TRAVEL_DATES = 'SET_TRAVEL_DATES';
export const SET_ACTIVE_USERS = 'SET_ACTIVE_USERS';
export const SET_USER_FILTERED_TODOS = 'SET_USER_FILTERED_TODOS';
export const SET_ACTIVE_TRANSLATE = 'SET_ACTIVE_TRANSLATE';
export const SET_FILTERED_TRANSLATIONS = 'SET_FILTERED_TRANSLATIONS';
